apiVersion: backstage.io/v1alpha1
kind: Component
metadata:
  name: alibaba-node-website
  description: Node.js service forked from Alibaba
  tags:
    - nodejs
    - alibaba
    - website
spec:
  type: website
  owner: team-a  # Update this with your team or organization
  lifecycle: production
  system: alibaba-website-systems
  links:
    - url: "https://github.com/ultracloud5652/ice"  # Link to the repository
      title: "Source Code"
    - url: "https://github.com/alibaba/ice"  # Link to the live website
      title: "Website"
    - url: "https://github.com/ultracloud5652/ice/blob/master/README.md"  # Link to documentation
      title: "Documentation"

  dependsOn:
    - resource: placeholder-database  # Placeholder for future dependencies
